language: go

go:
  - master

services:
  - docker

stages:
  - lint
  - test
  - publish

jobs:
  include:
    - stage: lint
      script: 
        - go get -u golang.org/x/lint/golint
        - go install golang.org/x/lint/golint
        - golint ./...
    - stage: test
      script: 
        - go get github.com/mattn/goveralls
        - go install github.com/mattn/goveralls
        - go test ./... -v -covermode=count -coverprofile coverage.out
        - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
    - stage: publish
      script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - docker build -t shotsfired/shots-store .
        - docker tag shotsfired/shots-store shotsfired/shots-store:latest
        - docker push shots-fired/shots-store

