language: go

go:
  - master

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script: 
        - go get -u golang.org/x/lint/golint
        - go install golang.org/x/lint/golint
        - golint ./...
    - stage: test
      script: go test ./...
