version: '3'
services:
    store:
        build: .
        restart: always
        depends_on:
        - redis
        ports:
        - "8888:8888"
    redis:
        image: redis:4-alpine
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        restart: always
        volumes:
        - ./store/conf/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
        - "6379:6379"
